Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          'themeBuilder':
            'colorPicker':
              type: string
              ui:
                showInCreationDialog: true
                reloadIfChanged: true
                inspector:
                  group: 'design'
                  editor: 'Shel.Neos.ColorPicker/ColorPickerEditor'
                  editorOptions:
                    mode: rgba
            'pixelRange':
              type: integer
              ui:
                showInCreationDialog: true
                reloadIfChanged: true
                inspector:
                  group: 'design'
                  editor: Neos.Neos/Inspector/Editors/RangeEditor
                  editorOptions:
                    min: 0
                    max: 100
                    step: 1
                    unit: px
            'numberRange':
              type: integer
              ui:
                showInCreationDialog: true
                reloadIfChanged: true
                inspector:
                  group: 'design'
                  editor: Neos.Neos/Inspector/Editors/RangeEditor
                  editorOptions:
                    min: 0
                    max: 100
                    step: 1
            'colorSelector':
              type: string
              ui:
                showInCreationDialog: true
                reloadIfChanged: true
                inspector:
                  group: 'design'
                  editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
                  editorOptions:
                    dataSourceIdentifier: 'shel-neos-themebuilder-theme-colors'
                    dataSourceDisableCaching: true
                    placeholder: 'Standard'
                    allowEmpty: true
